name: Tests & publish

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  format-and-lint-checker:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node LTS and Yarn using Volta
        run: |
          set -e
          curl https://get.volta.sh | bash
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          volta install node@lts
          volta install yarn
          yarn --version
          node --version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: corepack enable && echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Setup Yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        env:
          NODE_ENV: development
        run: yarn install --immutable

      - name: Run formatting and linting
        run: yarn format:check && yarn lint

  tests-and-compatibility:
    name: Test Node.js ${{ matrix.node-version }} + ESLint ${{ matrix.eslint-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["lts/-3", "lts/-2", "lts/-1", "latest"]
        eslint-version: ["8.0.0", "8.50.0", "9.0.0", "latest"]
        exclude:
          # ESLint 9 requires Node.js >= 18.18.0
          - node-version: "lts/-3"
            eslint-version: "9.0.0"
          - node-version: "lts/-3"
            eslint-version: "latest"
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install Node and Yarn using Volta
        run: |
          set -e
          curl https://get.volta.sh | bash
          export VOLTA_HOME="$HOME/.volta"
          export PATH="$VOLTA_HOME/bin:$PATH"
          volta install node@lts
          volta install yarn
          yarn --version
          node --version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: corepack enable && echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Setup Yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        env:
          NODE_ENV: development
        run: yarn install --immutable

      - name: Install ESLint ${{ matrix.eslint-version }}
        env:
          NODE_ENV: development
        run: |
          yarn add -D eslint@${{ matrix.eslint-version }}
          yarn add -D @typescript-eslint/parser@latest

      - name: Run tests
        env:
          NODE_ENV: development
        run: yarn test

  release:
      name: Release
      runs-on: ubuntu-latest
      needs:
        - format-and-lint-checker
        - tests-and-compatibility
      if: github.event_name != 'pull_request' && github.repository == 'MrZyr0/eslint-plugin-imports-perfectionist-order'
      permissions:
        contents: write # to be able to publish a GitHub release
        issues: write # to be able to comment on released issues
        pull-requests: write # to be able to comment on released pull requests
        id-token: write # to enable use of OIDC for trusted publishing and npm provenance
      environment: release
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0 # Important for semantic-release to analyze the complete history
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "lts/*"
            registry-url: 'https://registry.npmjs.org'

        - name: Clean legacy npm config
          run: npm config delete always-auth || true

        - name: Update NPM CLI
          run: npm install -g npm@latest

        - name: Install dependencies for semantic-release only
          run: |
            npm install -g \
            semantic-release \
            @semantic-release/changelog \
            @semantic-release/git \
            @semantic-release/github \
            @semantic-release/npm \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator

        - name: Create Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: npx semantic-release
